### ISSUE TITLE
log提示了这些信息

### ISSUE THREAD

**Issue by ohkimchi** [ZhaoxiZhang/LeetCodeCrawler#3]
我跑`java -jar LeetCodeCrawler.jar`出了下面的log
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 0.009345862418237686 at line 1 column 3257 path $.stat_status_pairs[6].frequency
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:228)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at OkHttpHelper.fromJson(OkHttpHelper.java:65)
	at Problem.getAllProblems(Problem.java:65)
	at Problem.getAllAcProblems(Problem.java:81)
	at Main.main(Main.java:17)
Caused by: java.lang.NumberFormatException: Expected an int but was 0.009345862418237686 at line 1 column 3257 path $.stat_status_pairs[6].frequency
	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1204)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:226)
	... 16 more

发生了什么？

**Comment by ZhaoxiZhang** [comment]
从日志来看，Gson解析错误，初步估计是拿到的Json数据中`stat_status_pairs`数组下的`frequency`字段并非是`int`类型，可以的话，请在登陆状态下，打开`https://leetcode.com/api/problems/all/`链接，帮忙看下你的数据下`frequency`是否是浮点型或者可以的话把得到的Json文件发送给我。

**Comment by ohkimchi** [comment]
好的，谢谢你！
[all.json.zip](https://github.com/ZhaoxiZhang/LeetCodeCrawler/files/3050328/all.json.zip)

**Comment by ohkimchi** [comment]
@ZhaoxiZhang 在哪里可以得到这些api，比如上面的/problems/all？

**Comment by ZhaoxiZhang** [comment]
目前的话 我还没看到有官方或者他人整理的完整的API集合，我是通过浏览器的开发者工具查找得到的API，另外也可以通过抓包工具得到，比如Fiddler。
从你发送的JSON文件，`frequency`字段和`progress`字段是浮点型的，之前从我自己的数据，我还以为是整型，晚点会更新代码~

**Comment by ohkimchi** [comment]
@ZhaoxiZhang 原来还可以抓包，谢谢你的信息！！嗯嗯 等待更新

**Comment by ZhaoxiZhang** [comment]
试一下这个看看行不行[LeetCodeCrawler.jar](https://github.com/ZhaoxiZhang/LeetCodeCrawler/raw/master/LeetCodeCrawler.jar)

**Comment by ohkimchi** [comment]
@ZhaoxiZhang 现在可以了，谢谢你！！
